- name: Test MD5 Verification
  hosts: all
  connection: network_cli
  vars:
    ansible_network_os: ios
    ios_cx_version: "15.2(7)E2"
    ios_file_3560_cx: c3560cx-universalk9-mz.152-7.E2.bin
    # ios_checksum_3560_cx: 17d91bba7d6f5780c491cd635685a260
    # ios_checksum_verify_3560_cx: "    verify /md5 (flash:{{ ios_file_3560_cx }}) = {{ ios_checksum_3560_cx }}"

  gather_facts: false

  tasks:
    - name: Verify MD5 Checksum of Image
      cisco.ios.ios_command:
        commands:
          - command: "verify /md5 flash:{{ ios_file_3560_cx }}"
        wait_for:
          - result[0] contains {{ ios_checksum_3560_cx }}
        retries: 1
      register: md5_check
      vars:
        ansible_command_timeout: 60

    - name: Change Boot Variable to new image
      cisco.ios.ios_config:
        commands:
          - "boot system flash:{{ ios_file_3560_cx }}"
        save_when: always
      when: md5_check
      register: boot_change
