---
# handlers file for cisco_updates

- name: cleanup ios xe packages
  cisco.ios.ios_command:
    commands:
      - command: "request platform software package clean switch all"
    prompt: Do you want to proceed? [y/n]
    answer: y
  vars:
    ansible_command_timeout: 120
