---
- name: Copy Image // This could take up to 4 minutes
  ansible.netcommon.net_put:
    src: "ios_files/{{ 3560_cg_ios_file }}"
    dest: "flash:/{{ 3560_cg_ios_file }}"
  vars:
    ansible_command_timeout: "{{ ios_copy_timeout }}"

- name: Change Boot Variable to new image
  cisco.ios.ios_config:
    commands:
      - "boot system flash:{{ 3560_cg_ios_file }}"
    save_when: always

- name: reboot ios device
  cli_command:
    command: reload
    prompt:
      - Save?
      - confirm
    answer:
      - y
      - y

- name: reset the connection
  meta: reset_connection

- name: Wait for the network device to reload
  wait_for_connection:
    delay: "{{ ios_reboot_timeout }}"

- name: Gather facts post reboot
  cisco.ios.ios_facts:
    gather_subset: min

- name: Assert that ios is the correct version
  assert:
    that:
      - ansible_net_version == {{ ios_version }}
  ignore_errors: True
