---
- name: Update TFTP Blocksize to optimize IOS transfer
  cisco.ios.ios_config:
    commands:
      - "ip tftp blocksize {{ tftp_blocksize }}"

- name: Copy 3560CX Image // This could take up to {{ ios_copy_timeout }} seconds
  # ansible.netcommon.net_put:
  #   src: "ios_files/{{ ios_file_3560_cx }}"
  #   dest: "flash:{{ ios_file_3560_cx }}"
  cisco.ios.ios_command:
    commands:
      - command: "copy tftp://{{ tftp_server }}/{{ ios_file_3560_cx }} flash:{{ ios_file_3560_cx }}"
        prompt:
          - "]?"
          - "[confirm]"
        answer:
          - "\r"
          - "\r"
  vars:
    ansible_command_timeout: "{{ ios_copy_timeout }}"

- name: Verify MD5 Checksum of Image
  cisco.ios.ios_command:
    commands:
      - command: "verify /md5 flash:{{ ios_file_3560_cx }}"
    wait_for:
      - result[0] contains {{ ios_checksum_3560_cx }}
    retries: 1
  register: md5_check
  vars:
    ansible_command_timeout: 60

- name: Change Boot Variable to new image
  cisco.ios.ios_config:
    commands:
      - "boot system flash:{{ ios_file_3560_cx }}"
    save_when: always
  when: md5_check
  register: boot_change

- name: reboot ios device
  cli_command:
    command: reload
    prompt:
      - Save?
      - confirm
    answer:
      - y
      - y
  when: boot_change.changed
  check_mode: true

- name: reset the connection
  meta: reset_connection

- name: Wait for the network device to reload
  wait_for_connection:
    delay: "{{ ios_reboot_timeout }}"
