---
# not necessary?
# - name: Update TFTP Blocksize to optimize IOS transfer
#   cisco.ios.ios_config:
#     commands:
#       - "ip tftp blocksize {{ tftp_blocksize }}"

- name: Copy 9000 Series Image // This could take up to {{ ios_xe_copy_timeout }} seconds
  # ansible.netcommon.net_put:
  #   src: "ios_files/{{ ios_file_3560_cx }}"
  #   dest: "flash:{{ ios_file_3560_cx }}"
  cisco.ios.ios_command:
    commands:
      - command: "copy tftp://{{ tftp_server }}/{{ ios_xe_file_9000 }} flash:{{ ios_xe_file_9000 }}"
        prompt:
          - "]?"
          - "[confirm]"
        answer:
          - "\r"
          - "\r"
  vars:
    ansible_command_timeout: "{{ ios_xe_copy_timeout }}"

- name: Verify MD5 Checksum of Image
  cisco.ios.ios_command:
    commands:
      - command: "verify /md5 flash:{{ ios_xe_file_9000 }}"
    wait_for:
      - result[0] contains {{ ios_xe_checksum_9000 }}
    retries: 1
  register: md5_check
  vars:
    ansible_command_timeout: 60

- name: Change Boot Variable to new image
  cisco.ios.ios_config:
    commands:
      - "boot system flash:packages.conf"
    save_when: always
  when: md5_check
  register: boot_change

- name: Activate new image
  cisco.ios.ios_command:
    commands:
      - command: "install add file flash:{{ ios_xe_file_9000 }} activate commit"
    prompt:
      - This operation requires a reload of the system. Do you want to proceed? [y/n]
    answer: y
  register: boot_change
  when: package_install_single or package_install_stack
  vars:
    ansible_command_timeout: "{{ ios_xe_copy_timeout }}"

- name: reset the connection
  meta: reset_connection

- name: Wait for the network device to reload
  wait_for_connection:
    delay: "{{ ios_xe_reboot_timeout }}"
  notify: cleanup ios xe packages
